kind: ConfigMap
apiVersion: v1
metadata:
  name: horizontal-pod-autoscalers
  namespace: kube-public
  labels:
    app.kubernetes.io/name: horizontal-pod-autoscalers
    busola.io/extension: resource
    busola.io/extension-version: '0.5'
data:
  dataSources: |
    myEvents:
      resource:
        kind: Event
        group: events.k8s.io
        version: v1
  details: |-
    header:
      - name: Status
        source: status.conditions.type
        widget: Labels
    body:
      - name: Specification
        widget: Panel
        children:
          - name: Min Pods
            source: spec.minReplicas
          - name: Current Replicas
            source: status.currentReplicas
          - name: Max Pods
            source: spec.maxReplicas
          - name: Scale Target Reference
            source: spec.scaleTargetRef
            widget: ControlledBy
      - name: Metrics
        widget: Panel
        children:
          - name: Resource memory on Pods
            visibility: $count($filter(status.currentMetrics, function($v, $i, $a) {$v.resource.name = "memory"})) > 0
            source: |
                    $join([$string($filter(status.currentMetrics, function($v, $i, $a) {
                      $v.resource.name = "memory"})[0].resource.current.averageUtilization),'% / ',
                          $string($filter(spec.metrics, function($v, $i, $a) {
                      $v.resource.name = "memory"})[0].resource.target.averageUtilization),'%'])
          - name: Resource CPU on Pods
            visibility: $count($filter(status.currentMetrics, function($v, $i, $a) {$v.resource.name = "cpu"})) > 0
            source: |
                    $join([$string($filter(status.currentMetrics, function($v, $i, $a) {
                      $v.resource.name = "cpu"})[0].resource.current.averageUtilization),'% / ',
                          $string($single(spec.metrics, function($v, $i, $a) {
                      $v.resource.name = "cpu"}).resource.target.averageUtilization),'%'])
      - name: Events
        source: '$myEvents()'
        widget: ResourceList
  form: |-
    - name: Scale Target Reference
      simple: true
      path: spec.scaleTargetRef
      widget: FormGroup
      required: true
      defaultExpanded: true
      children:
        - simple: true
          required: true
          path: kind
          enum:
            - Pod
            - Deployment
            - ReplicaSet
        - simple: true
          required: true
          path: name
        - simple: true
          required: true
          path: apiVersion
    - name: Metrics
      simple: true
      required: true
      path: spec.metrics
      widget: GenericList
      defaultExpanded: true
      children:
        - path: '[].type'
          simple: true
          enum:
            - ContainerResource
            - External
            - Object
            - Pods
            - Resource
        - path: '[].port'
    - name: Min Pods
      simple: true
      required: true
      path: spec.minReplicas
    - name: Max Pods
      simple: true
      required: true
      path: spec.maxReplicas
  general: |-
    resource: 
      kind: HorizontalPodAutoscaler
      group: autoscaling
      version: v2
    name: Horizontal Pod Autoscalers
    category: Discovery and Network
    urlPath: horizontalpodautoscalers-x
    scope: namespace
    description: >-
      {{[Horizontal Pod Autoscalers](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/)}}
      automatically manages the number of Pod replicas to match the demand.
  list: |-
    - name: Metrics
      source: |
              $join([$string(status.currentMetrics[0].resource.current.averageUtilization),'% / ',
                  $string(spec.metrics[0].resource.target.averageUtilization),'%',$count(spec.metrics) > 1 ? ' and 1 more' : ''])
    - name: Min Pods
      source: spec.minReplicas
    - name: Max Pods
      source: spec.maxReplicas
    - name: Replicas
      source: status.currentReplicas
    - name: Status
      source: status.conditions.type
      widget: Labels
  presets: |-
    - name: Default
      default: true
      value: 
        spec:
          minReplicas: 1
          maxReplicas: 10
          metrics:
          - type: ''
  translations: |-
    en:
      metadata.annotations: Annotations
      metadata.labels: Labels
      metadata.creationTimestamp: Created at
