kind: ConfigMap
apiVersion: v1
metadata:
  name: horizontal-pod-autoscalers
  namespace: kube-public
  labels:
    app.kubernetes.io/name: horizontal-pod-autoscalers
    busola.io/extension: resource
    busola.io/extension-version: '0.5'
data:
  dataSources: ''
  details: |-
    header:
      - name: status
        source: $filter(status.conditions, function($v, $i, $a) {$v.status = 'True'}).type
        widget: Labels
    body:
      - name: specification
        widget: Panel
        children:
          - name: minReplicas
            source: spec.minReplicas
          - name: currentReplicas
            source: status.currentReplicas
          - name: maxReplicas
            source: spec.maxReplicas
          - name: scaleTargetReference
            source: spec.scaleTargetRef
            widget: ControlledBy
      - name: metrics
        widget: Panel
        children:
          - name: Resource memory on Pods
            visibility: $count($filter(status.currentMetrics, function($v, $i, $a) {$v.resource.name = "memory"})) > 0
            source: |
                    $join([$string($filter(status.currentMetrics, function($v, $i, $a) {
                      $v.resource.name = "memory"})[0].resource.current.averageUtilization),'% / ',
                          $string($filter(spec.metrics, function($v, $i, $a) {
                      $v.resource.name = "memory"})[0].resource.target.averageUtilization),'%'])
          - name: Resource CPU on Pods
            visibility: $count($filter(status.currentMetrics, function($v, $i, $a) {$v.resource.name = "cpu"})) > 0
            source: |
                    $join([$string($filter(status.currentMetrics, function($v, $i, $a) {
                      $v.resource.name = "cpu"})[0].resource.current.averageUtilization),'% / ',
                          $string($single(spec.metrics, function($v, $i, $a) {
                      $v.resource.name = "cpu"}).resource.target.averageUtilization),'%'])
      - widget: EventList
        filter: $matchEvents($item, $root.kind, $root.metadata.name)
        name: events
        defaultType: information
        hideInvolvedObjects: true
  form: |-
    - name: minReplicas
      simple: true
      path: spec.minReplicas
    - name: maxReplicas
      simple: true
      required: true
      path: spec.maxReplicas
    - path: spec.behavior
      widget: FormGroup
      defaultExpanded: true
      children:
        - path: scaleDown
          widget: FormGroup
          children:
            - path: selectPolicy
              enum:
                - Min
                - Max
                - Disabled
            - path: stabilizationWindowSeconds
            - path: policies
              defaultExpanded: true
              widget: GenericList
              children:
                - path: '[].type'
                  enum:
                    - Pods
                    - Percent
                - path: '[].value'
                - path: '[].periodSeconds'
        - path: scaleUp
          widget: FormGroup
          children:
            - path: selectPolicy
              enum:
                - Min
                - Max
                - Disabled
            - path: stabilizationWindowSeconds
            - path: policies
              defaultExpanded: true
              widget: GenericList
              children:
                - path: '[].type'
                  enum:
                    - Pods
                    - Percent
                - path: '[].value'
                - path: '[].periodSeconds'
                  defaultValue: 0
    - name: scaleTargetReference
      simple: true
      path: spec.scaleTargetRef
      widget: FormGroup
      required: true
      defaultExpanded: true
      children:
        - simple: true
          required: true
          path: kind
          enum:
            - Pod
            - Deployment
            - ReplicaSet
        - simple: true
          required: true
          path: name
        - name: apiVersion
          simple: true
          path: apiVersion
    - path: spec.metrics
      simple: true
      widget: GenericList
      defaultExpanded: true
      children:
        - simple: true
          path: '[].type'
          required: true
          enum:
            - Resource
            - Pods
            - Object
            - External
        - path: '[].resource.name'
          simple: true
          enum:
            - cpu
            - memory
          visibility: "$item.type = 'Resource'" 
        - path: '[].resource.target'
          widget: FormGroup
          simple: true
          visibility: "$item.type = 'Resource'"
          defaultExpanded: true
          children:
            - path: type
              simple: true
              enum:
                - Utilization
                - AverageValue
                - Value
            - path: averageUtilization
              simple: true
              visibility: "$item.resource.target.type = 'Utilization'"
            - path: averageValue
              simple: true
              visibility: "$item.resource.target.type = 'AverageValue'"
            - path: value
              simple: true
              visibility: "$item.resource.target.type = 'Value'"
        - path: '[].pods.metric.name'
          simple: true
          enum:
            - packets-per-second
          visibility: "$item.type = 'Pods'"
        - path: '[].pods.metric.selector.matchLabels'
          visibility: "$item.type = 'Pods'"
          widget: KeyValuePair
        - path: '[].pods.target'
          widget: FormGroup
          simple: true
          visibility: "$item.type = 'Pods'"
          defaultExpanded: true
          children:
            - path: type
              simple: true
              enum:
                - Utilization
                - AverageValue
                - Value
            - path: averageUtilization
              simple: true
              visibility: "$item.pods.target.type = 'Utilization'"
            - path: averageValue
              simple: true
              visibility: "$item.pods.target.type = 'AverageValue'"
            - path: value
              simple: true
              visibility: "$item.pods.target.type = 'Value'"
        - path: '[].object.metric.name'
          simple: true
          enum:
            - requests-per-second
          visibility: "$item.type = 'Object'"
        - path: '[].object.metric.selector.matchLabels'
          visibility: "$item.type = 'Object'"
          widget: KeyValuePair
        - path: '[].object.describedObject'
          widget: FormGroup
          simple: true
          visibility: "$item.type = 'Object'"
          defaultExpanded: true
          children:
            - path: kind
              simple: true
              required: true
            - path: name
              simple: true
              required: true
            - name: apiVersion
              path: apiVersion
              simple: true
        - path: '[].object.target'
          widget: FormGroup
          simple: true
          visibility: "$item.type = 'Object'"
          defaultExpanded: true
          children:
            - path: type
              simple: true
              enum:
                - Utilization
                - AverageValue
                - Value
            - path: averageUtilization
              simple: true
              visibility: "$item.object.target.type = 'Utilization'"
            - path: averageValue
              simple: true
              visibility: "$item.object.target.type = 'AverageValue'"
            - path: value
              simple: true
              visibility: "$item.object.target.type = 'Value'"
        - path: '[].external.metric.name'
          simple: true
          enum:
            - requests-per-second
          visibility: "$item.type = 'External'"
        - path: '[].external.metric.selector.matchLabels'
          visibility: "$item.type = 'External'"
          widget: KeyValuePair
        - path: '[].external.target'
          widget: FormGroup
          simple: true
          visibility: "$item.type = 'External'"
          defaultExpanded: true
          children:
            - path: type
              simple: true
              enum:
                - Utilization
                - AverageValue
                - Value
            - path: averageUtilization
              simple: true
              visibility: "$item.external.target.type = 'Utilization'"
            - path: averageValue
              simple: true
              visibility: "$item.external.target.type = 'AverageValue'"
            - path: value
              simple: true
              visibility: "$item.external.target.type = 'Value'"
  general: |-
    resource: 
      kind: HorizontalPodAutoscaler
      group: autoscaling
      version: v2
    name: Horizontal Pod Autoscalers
    category: Discovery and Network
    urlPath: horizontalpodautoscalers
    scope: namespace
    description: >-
      {{[Horizontal Pod Autoscalers](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/)}}
      automatically manages the number of Pod replicas to match the demand.
  list: |-
    - name: metrics
      source: |
              $join([$string(status.currentMetrics[0].resource.current.averageUtilization),'% / ',
                  $string(spec.metrics[0].resource.target.averageUtilization),'%',$count(spec.metrics) > 1 ? ' and 1 more' : ''])
    - name: minReplicas
      source: spec.minReplicas
    - name: maxReplicas
      source: spec.maxReplicas
    - name: currentReplicas
      source: status.currentReplicas
    - name: status
      source: $filter(status.conditions, function($v, $i, $a) {$v.status = 'True'}).type
      widget: Labels
  presets: |-
    - name: Default
      default: true
      value: 
        spec:
          minReplicas: 1
          maxReplicas: 10
  translations: |-
    en:
      metadata.annotations: Annotations
      metadata.labels: Labels
      metadata.creationTimestamp: Created at
      status: Status
      currentReplicas: Current Replicas
      minReplicas: Min Replicas
      maxReplicas: Max Replicas
      metrics: Metrics
      apiVersion: API version
      scaleTargetReference: Scale Target Reference
      events: Events
      specification: Specification
